// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package sqlc

import (
	"database/sql"
)

type Agent struct {
	ID                   string `json:"id"`
	Name                 string `json:"name"`
	Model                string `json:"model"`
	ModelStrong          string `json:"model_strong"`
	ModelFast            string `json:"model_fast"`
	SystemPrompt         string `json:"system_prompt"`
	Soul                 string `json:"soul"`
	Workspace            string `json:"workspace"`
	Sandbox              string `json:"sandbox"`
	EnabledBuiltinSkills string `json:"enabled_builtin_skills"`
	Scope                string `json:"scope"`
	CreatorID            string `json:"creator_id"`
	Enabled              int64  `json:"enabled"`
	CreatedAt            string `json:"created_at"`
	UpdatedAt            string `json:"updated_at"`
}

type AgentGoal struct {
	ID             string         `json:"id"`
	UserID         string         `json:"user_id"`
	AgentID        sql.NullString `json:"agent_id"`
	Title          string         `json:"title"`
	Description    string         `json:"description"`
	Status         string         `json:"status"`
	Priority       string         `json:"priority"`
	ReviewPolicy   string         `json:"review_policy"`
	ActiveReviewID sql.NullString `json:"active_review_id"`
	Context        string         `json:"context"`
	Output         string         `json:"output"`
	CreatedAt      string         `json:"created_at"`
	UpdatedAt      string         `json:"updated_at"`
	CompletedAt    sql.NullString `json:"completed_at"`
	CancelledAt    sql.NullString `json:"cancelled_at"`
}

type AgentReview struct {
	ID                    string         `json:"id"`
	TaskID                sql.NullString `json:"task_id"`
	GoalID                sql.NullString `json:"goal_id"`
	SubmittedRunID        sql.NullString `json:"submitted_run_id"`
	ReviewerRunID         sql.NullString `json:"reviewer_run_id"`
	ReviewerType          string         `json:"reviewer_type"`
	ReviewerUserID        sql.NullString `json:"reviewer_user_id"`
	EscalatedFromReviewID sql.NullString `json:"escalated_from_review_id"`
	Status                string         `json:"status"`
	Summary               string         `json:"summary"`
	Feedback              string         `json:"feedback"`
	CreatedAt             string         `json:"created_at"`
	UpdatedAt             string         `json:"updated_at"`
	ResolvedAt            sql.NullString `json:"resolved_at"`
}

type AgentReviewItem struct {
	ID          string         `json:"id"`
	ReviewID    string         `json:"review_id"`
	CriterionID sql.NullString `json:"criterion_id"`
	Passed      sql.NullInt64  `json:"passed"`
	Evidence    string         `json:"evidence"`
	CreatedAt   string         `json:"created_at"`
}

type AgentTask struct {
	ID              string         `json:"id"`
	UserID          string         `json:"user_id"`
	AgentID         sql.NullString `json:"agent_id"`
	GoalID          sql.NullString `json:"goal_id"`
	Title           string         `json:"title"`
	Description     string         `json:"description"`
	Status          string         `json:"status"`
	Priority        string         `json:"priority"`
	ReviewPolicy    string         `json:"review_policy"`
	ActiveReviewID  sql.NullString `json:"active_review_id"`
	Required        int64          `json:"required"`
	RetryCount      int64          `json:"retry_count"`
	MaxRetries      int64          `json:"max_retries"`
	NotBefore       sql.NullString `json:"not_before"`
	DeadlineAt      sql.NullString `json:"deadline_at"`
	SessionID       sql.NullString `json:"session_id"`
	ActiveRunID     sql.NullString `json:"active_run_id"`
	ActiveBlockerID sql.NullString `json:"active_blocker_id"`
	Context         string         `json:"context"`
	Output          string         `json:"output"`
	CreatedAt       string         `json:"created_at"`
	UpdatedAt       string         `json:"updated_at"`
	CompletedAt     sql.NullString `json:"completed_at"`
	CancelledAt     sql.NullString `json:"cancelled_at"`
}

type AgentTaskBlocker struct {
	ID             string         `json:"id"`
	TaskID         string         `json:"task_id"`
	Kind           string         `json:"kind"`
	Status         string         `json:"status"`
	Question       string         `json:"question"`
	Detail         string         `json:"detail"`
	Resolution     string         `json:"resolution"`
	CreatedByRunID sql.NullString `json:"created_by_run_id"`
	CreatedAt      string         `json:"created_at"`
	ResolvedAt     sql.NullString `json:"resolved_at"`
}

type AgentTaskCriterion struct {
	ID           string `json:"id"`
	TaskID       string `json:"task_id"`
	Description  string `json:"description"`
	RequiredFlag int64  `json:"required_flag"`
	Position     int64  `json:"position"`
	CreatedAt    string `json:"created_at"`
}

type AgentTaskDep struct {
	TaskID       string         `json:"task_id"`
	DepTaskID    string         `json:"dep_task_id"`
	DepKind      string         `json:"dep_kind"`
	OnFailure    string         `json:"on_failure"`
	WaivedAt     sql.NullString `json:"waived_at"`
	WaivedByUser sql.NullString `json:"waived_by_user"`
	WaiverReason string         `json:"waiver_reason"`
	CreatedAt    string         `json:"created_at"`
}

type AgentTaskDispatchHint struct {
	ID              string         `json:"id"`
	TaskID          sql.NullString `json:"task_id"`
	GoalID          sql.NullString `json:"goal_id"`
	Kind            string         `json:"kind"`
	ExecutorAgentID string         `json:"executor_agent_id"`
	ConsumedAt      sql.NullString `json:"consumed_at"`
	CreatedAt       string         `json:"created_at"`
}

type AgentTaskEvent struct {
	ID         string         `json:"id"`
	TaskID     sql.NullString `json:"task_id"`
	GoalID     sql.NullString `json:"goal_id"`
	RunID      sql.NullString `json:"run_id"`
	BlockerID  sql.NullString `json:"blocker_id"`
	ReviewID   sql.NullString `json:"review_id"`
	EventType  string         `json:"event_type"`
	FromStatus sql.NullString `json:"from_status"`
	ToStatus   sql.NullString `json:"to_status"`
	ActorType  string         `json:"actor_type"`
	ActorID    sql.NullString `json:"actor_id"`
	Detail     string         `json:"detail"`
	CreatedAt  string         `json:"created_at"`
}

type AgentTaskRun struct {
	ID              string         `json:"id"`
	TaskID          sql.NullString `json:"task_id"`
	GoalID          sql.NullString `json:"goal_id"`
	UserID          string         `json:"user_id"`
	AgentID         sql.NullString `json:"agent_id"`
	ExecutorAgentID sql.NullString `json:"executor_agent_id"`
	Kind            string         `json:"kind"`
	AttemptNo       int64          `json:"attempt_no"`
	Status          string         `json:"status"`
	SessionID       string         `json:"session_id"`
	Input           string         `json:"input"`
	Result          string         `json:"result"`
	Error           string         `json:"error"`
	HeartbeatAt     sql.NullString `json:"heartbeat_at"`
	LeaseExpiresAt  sql.NullString `json:"lease_expires_at"`
	WorkerID        string         `json:"worker_id"`
	StartedAt       sql.NullString `json:"started_at"`
	FinishedAt      sql.NullString `json:"finished_at"`
	CreatedAt       string         `json:"created_at"`
	UpdatedAt       string         `json:"updated_at"`
}

type AppSetting struct {
	Key       string `json:"key"`
	Value     string `json:"value"`
	CreatedAt string `json:"created_at"`
	UpdatedAt string `json:"updated_at"`
}

type AuthCredential struct {
	ID           string `json:"id"`
	UserID       string `json:"user_id"`
	PasswordHash string `json:"password_hash"`
	CreatedAt    string `json:"created_at"`
	UpdatedAt    string `json:"updated_at"`
}

type AuthIdentity struct {
	ID              string `json:"id"`
	UserID          string `json:"user_id"`
	Provider        string `json:"provider"`
	ProviderSubject string `json:"provider_subject"`
	Email           string `json:"email"`
	Name            string `json:"name"`
	AvatarUrl       string `json:"avatar_url"`
	RawClaims       string `json:"raw_claims"`
	CreatedAt       string `json:"created_at"`
	UpdatedAt       string `json:"updated_at"`
}

type AuthOidcAccessToken struct {
	ID        string `json:"id"`
	TokenHash string `json:"token_hash"`
	UserID    string `json:"user_id"`
	ClientID  string `json:"client_id"`
	Scopes    string `json:"scopes"`
	ExpiresAt string `json:"expires_at"`
	CreatedAt string `json:"created_at"`
}

type AuthOidcCode struct {
	ID            string         `json:"id"`
	CodeHash      string         `json:"code_hash"`
	UserID        string         `json:"user_id"`
	ClientID      string         `json:"client_id"`
	RedirectUri   string         `json:"redirect_uri"`
	Scopes        string         `json:"scopes"`
	Nonce         string         `json:"nonce"`
	PkceChallenge string         `json:"pkce_challenge"`
	PkceMethod    string         `json:"pkce_method"`
	ExpiresAt     string         `json:"expires_at"`
	ConsumedAt    sql.NullString `json:"consumed_at"`
	CreatedAt     string         `json:"created_at"`
}

type AuthPolicy struct {
	ID         string `json:"id"`
	Name       string `json:"name"`
	Effect     string `json:"effect"`
	Subjects   string `json:"subjects"`
	Actions    string `json:"actions"`
	Resources  string `json:"resources"`
	Conditions string `json:"conditions"`
	Priority   int64  `json:"priority"`
	IsSystem   int64  `json:"is_system"`
	Enabled    int64  `json:"enabled"`
	CreatedAt  string `json:"created_at"`
	UpdatedAt  string `json:"updated_at"`
}

type AuthSession struct {
	ID        string `json:"id"`
	UserID    string `json:"user_id"`
	TokenHash string `json:"token_hash"`
	ExpiresAt string `json:"expires_at"`
	CreatedAt string `json:"created_at"`
	UpdatedAt string `json:"updated_at"`
}

type AuthUser struct {
	ID               string         `json:"id"`
	Email            string         `json:"email"`
	Name             string         `json:"name"`
	AvatarUrl        string         `json:"avatar_url"`
	Role             string         `json:"role"`
	IsActive         int64          `json:"is_active"`
	DefaultAgentID   sql.NullString `json:"default_agent_id"`
	NotifyIdentityID sql.NullString `json:"notify_identity_id"`
	AgePublicKey     string         `json:"age_public_key"`
	AgePrivateKey    string         `json:"age_private_key"`
	CreatedAt        string         `json:"created_at"`
	UpdatedAt        string         `json:"updated_at"`
}

type AuthUserAgent struct {
	UserID  string `json:"user_id"`
	AgentID string `json:"agent_id"`
}

type AuthUserToken struct {
	ID            string         `json:"id"`
	UserID        string         `json:"user_id"`
	Name          string         `json:"name"`
	TokenHash     string         `json:"token_hash"`
	TokenPrefix   string         `json:"token_prefix"`
	AutoGenerated int64          `json:"auto_generated"`
	LastUsedAt    sql.NullString `json:"last_used_at"`
	ExpiresAt     sql.NullString `json:"expires_at"`
	RotatedAt     sql.NullString `json:"rotated_at"`
	RevokedAt     sql.NullString `json:"revoked_at"`
	CreatedAt     string         `json:"created_at"`
	UpdatedAt     string         `json:"updated_at"`
}

type Channel struct {
	ID        string         `json:"id"`
	Name      string         `json:"name"`
	Type      string         `json:"type"`
	AgentID   sql.NullString `json:"agent_id"`
	Enabled   int64          `json:"enabled"`
	Config    string         `json:"config"`
	CreatedAt string         `json:"created_at"`
	UpdatedAt string         `json:"updated_at"`
}

type ChannelAgent struct {
	ChannelID string `json:"channel_id"`
	Platform  string `json:"platform"`
	ChatID    string `json:"chat_id"`
	AgentID   string `json:"agent_id"`
	CreatedAt string `json:"created_at"`
	UpdatedAt string `json:"updated_at"`
}

type ChannelIdentity struct {
	ID         string `json:"id"`
	UserID     string `json:"user_id"`
	Platform   string `json:"platform"`
	ExternalID string `json:"external_id"`
	Name       string `json:"name"`
	CreatedAt  string `json:"created_at"`
	UpdatedAt  string `json:"updated_at"`
}

type CtxAgentMemory struct {
	UserID      string `json:"user_id"`
	AgentID     string `json:"agent_id"`
	Content     string `json:"content"`
	Soul        string `json:"soul"`
	Version     int64  `json:"version"`
	Constraints string `json:"constraints"`
	CreatedAt   string `json:"created_at"`
	UpdatedAt   string `json:"updated_at"`
}

type CtxAgentMemoryChangelog struct {
	ID                  string         `json:"id"`
	UserID              string         `json:"user_id"`
	AgentID             string         `json:"agent_id"`
	SessionID           sql.NullString `json:"session_id"`
	EntityID            sql.NullString `json:"entity_id"`
	Scope               string         `json:"scope"`
	Action              string         `json:"action"`
	Source              string         `json:"source"`
	MemoryVersionBefore sql.NullInt64  `json:"memory_version_before"`
	MemoryVersionAfter  sql.NullInt64  `json:"memory_version_after"`
	BeforeText          sql.NullString `json:"before_text"`
	AfterText           sql.NullString `json:"after_text"`
	Metadata            sql.NullString `json:"metadata"`
	CreatedAt           string         `json:"created_at"`
}

type CtxAgentMemorySnapshot struct {
	SessionID string `json:"session_id"`
	UserID    string `json:"user_id"`
	AgentID   string `json:"agent_id"`
	Version   int64  `json:"version"`
	CreatedAt string `json:"created_at"`
	UpdatedAt string `json:"updated_at"`
}

type CtxConversation struct {
	ID             string         `json:"id"`
	SessionID      string         `json:"session_id"`
	Title          sql.NullString `json:"title"`
	Channel        string         `json:"channel"`
	Kind           string         `json:"kind"`
	ProjectID      sql.NullString `json:"project_id"`
	Archived       int64          `json:"archived"`
	LastActive     string         `json:"last_active"`
	BootstrappedAt sql.NullString `json:"bootstrapped_at"`
	AgentID        sql.NullString `json:"agent_id"`
	UserID         sql.NullString `json:"user_id"`
	CreatedAt      string         `json:"created_at"`
	UpdatedAt      string         `json:"updated_at"`
}

type CtxItem struct {
	ConversationID string         `json:"conversation_id"`
	Ordinal        int64          `json:"ordinal"`
	ItemType       string         `json:"item_type"`
	MessageID      sql.NullString `json:"message_id"`
	SummaryID      sql.NullString `json:"summary_id"`
	CreatedAt      string         `json:"created_at"`
}

type CtxMessage struct {
	ID             string `json:"id"`
	ConversationID string `json:"conversation_id"`
	Seq            int64  `json:"seq"`
	Role           string `json:"role"`
	EventType      string `json:"event_type"`
	Content        string `json:"content"`
	TokenCount     int64  `json:"token_count"`
	CreatedAt      string `json:"created_at"`
}

type CtxMessagePart struct {
	ID          string         `json:"id"`
	MessageID   string         `json:"message_id"`
	PartType    string         `json:"part_type"`
	Ordinal     int64          `json:"ordinal"`
	TextContent sql.NullString `json:"text_content"`
	ToolCallID  sql.NullString `json:"tool_call_id"`
	ToolName    sql.NullString `json:"tool_name"`
	ToolInput   sql.NullString `json:"tool_input"`
	ToolOutput  sql.NullString `json:"tool_output"`
	Metadata    sql.NullString `json:"metadata"`
}

type CtxSummary struct {
	ID                      string         `json:"id"`
	ConversationID          string         `json:"conversation_id"`
	Kind                    string         `json:"kind"`
	Depth                   int64          `json:"depth"`
	Content                 string         `json:"content"`
	TokenCount              int64          `json:"token_count"`
	EarliestAt              sql.NullString `json:"earliest_at"`
	LatestAt                sql.NullString `json:"latest_at"`
	DescendantCount         int64          `json:"descendant_count"`
	DescendantTokenCount    int64          `json:"descendant_token_count"`
	SourceMessageTokenCount int64          `json:"source_message_token_count"`
	CreatedAt               string         `json:"created_at"`
}

type CtxSummaryMessage struct {
	SummaryID string `json:"summary_id"`
	MessageID string `json:"message_id"`
	Ordinal   int64  `json:"ordinal"`
}

type CtxSummaryParent struct {
	SummaryID       string `json:"summary_id"`
	ParentSummaryID string `json:"parent_summary_id"`
	Ordinal         int64  `json:"ordinal"`
}

type Plugin struct {
	ID        string `json:"id"`
	Kind      string `json:"kind"`
	Name      string `json:"name"`
	Enabled   int64  `json:"enabled"`
	Config    string `json:"config"`
	CreatedAt string `json:"created_at"`
	UpdatedAt string `json:"updated_at"`
}

type PluginOauthProvider struct {
	ID              string `json:"id"`
	ProviderID      string `json:"provider_id"`
	ClientID        string `json:"client_id"`
	ClientSecretEnc string `json:"client_secret_enc"`
	RedirectUrl     string `json:"redirect_url"`
	CreatedAt       string `json:"created_at"`
	UpdatedAt       string `json:"updated_at"`
}

type PluginOverride struct {
	PluginID           string        `json:"plugin_id"`
	Enabled            sql.NullInt64 `json:"enabled"`
	SessionEnvVaultKey string        `json:"session_env_vault_key"`
	Config             string        `json:"config"`
	CreatedAt          string        `json:"created_at"`
	UpdatedAt          string        `json:"updated_at"`
}

type PluginState struct {
	PluginID  string `json:"plugin_id"`
	ScopeKind string `json:"scope_kind"`
	ScopeID   string `json:"scope_id"`
	StateKey  string `json:"state_key"`
	Value     string `json:"value"`
	CreatedAt string `json:"created_at"`
	UpdatedAt string `json:"updated_at"`
}

type Project struct {
	ID          string         `json:"id"`
	AgentID     string         `json:"agent_id"`
	UserID      string         `json:"user_id"`
	Name        string         `json:"name"`
	BaseDir     string         `json:"base_dir"`
	Description sql.NullString `json:"description"`
	Archived    int64          `json:"archived"`
	CreatedAt   string         `json:"created_at"`
	UpdatedAt   string         `json:"updated_at"`
}

type Provider struct {
	ID        string `json:"id"`
	Type      string `json:"type"`
	Name      string `json:"name"`
	Enabled   int64  `json:"enabled"`
	Config    string `json:"config"`
	CreatedAt string `json:"created_at"`
	UpdatedAt string `json:"updated_at"`
}

type RecallyArticle struct {
	ID           string         `json:"id"`
	UserID       string         `json:"user_id"`
	AgentID      sql.NullString `json:"agent_id"`
	Url          string         `json:"url"`
	CanonicalUrl string         `json:"canonical_url"`
	SourceType   string         `json:"source_type"`
	Title        string         `json:"title"`
	Author       string         `json:"author"`
	Summary      string         `json:"summary"`
	Tags         string         `json:"tags"`
	Status       string         `json:"status"`
	Starred      int64          `json:"starred"`
	FilePath     string         `json:"file_path"`
	Metadata     string         `json:"metadata"`
	PublishedAt  sql.NullString `json:"published_at"`
	SavedAt      string         `json:"saved_at"`
	ReadAt       sql.NullString `json:"read_at"`
	CreatedAt    string         `json:"created_at"`
	UpdatedAt    string         `json:"updated_at"`
}

type RecallyDigest struct {
	ID                   string `json:"id"`
	UserID               string `json:"user_id"`
	Date                 string `json:"date"`
	Narrative            string `json:"narrative"`
	SavedYesterdayCount  int64  `json:"saved_yesterday_count"`
	UnreadCount          int64  `json:"unread_count"`
	ReadCount            int64  `json:"read_count"`
	ArchivedCount        int64  `json:"archived_count"`
	StarredCount         int64  `json:"starred_count"`
	WorthRevisitingCount int64  `json:"worth_revisiting_count"`
	TotalArticles        int64  `json:"total_articles"`
	TopTags              string `json:"top_tags"`
	CreatedAt            string `json:"created_at"`
	UpdatedAt            string `json:"updated_at"`
}

type RecallyDigestArticle struct {
	DigestID  string `json:"digest_id"`
	ArticleID string `json:"article_id"`
	Section   string `json:"section"`
	Position  int64  `json:"position"`
}

type RecallyRssFeed struct {
	ID            string         `json:"id"`
	UserID        string         `json:"user_id"`
	AgentID       sql.NullString `json:"agent_id"`
	Url           string         `json:"url"`
	Title         string         `json:"title"`
	Description   string         `json:"description"`
	CheckInterval string         `json:"check_interval"`
	LastCheckedAt sql.NullString `json:"last_checked_at"`
	LastEtag      string         `json:"last_etag"`
	LastModified  string         `json:"last_modified"`
	Enabled       int64          `json:"enabled"`
	CreatedAt     string         `json:"created_at"`
	UpdatedAt     string         `json:"updated_at"`
}

type RecallyRssFeedEntry struct {
	ID           string         `json:"id"`
	FeedID       string         `json:"feed_id"`
	Guid         string         `json:"guid"`
	Url          string         `json:"url"`
	Title        string         `json:"title"`
	Status       string         `json:"status"`
	ArticleID    sql.NullString `json:"article_id"`
	Attempts     int64          `json:"attempts"`
	ErrorMsg     string         `json:"error_msg"`
	DiscoveredAt string         `json:"discovered_at"`
	ProcessedAt  sql.NullString `json:"processed_at"`
}

type SchedJob struct {
	ID            string         `json:"id"`
	OwnerKind     string         `json:"owner_kind"`
	ExecScope     string         `json:"exec_scope"`
	PluginID      string         `json:"plugin_id"`
	JobKey        string         `json:"job_key"`
	RuntimeName   string         `json:"runtime_name"`
	Name          string         `json:"name"`
	Description   string         `json:"description"`
	ScheduleCron  string         `json:"schedule_cron"`
	ScheduleEvery string         `json:"schedule_every"`
	ScheduleAt    string         `json:"schedule_at"`
	Message       string         `json:"message"`
	Payload       string         `json:"payload"`
	SessionMode   string         `json:"session_mode"`
	Enabled       int64          `json:"enabled"`
	AgentID       sql.NullString `json:"agent_id"`
	UserID        sql.NullString `json:"user_id"`
	CreatedAt     string         `json:"created_at"`
	UpdatedAt     string         `json:"updated_at"`
	LastRunAt     sql.NullString `json:"last_run_at"`
	LastError     string         `json:"last_error"`
}

type SchedJobRun struct {
	ID         string         `json:"id"`
	JobID      string         `json:"job_id"`
	SessionID  string         `json:"session_id"`
	Status     string         `json:"status"`
	StartedAt  string         `json:"started_at"`
	FinishedAt sql.NullString `json:"finished_at"`
	Error      string         `json:"error"`
	UserID     sql.NullString `json:"user_id"`
}

type Share struct {
	ID        string         `json:"id"`
	TokenHash string         `json:"token_hash"`
	UserID    string         `json:"user_id"`
	Title     string         `json:"title"`
	MediaType string         `json:"media_type"`
	Content   []byte         `json:"content"`
	ExpiresAt sql.NullString `json:"expires_at"`
	CreatedAt string         `json:"created_at"`
	UpdatedAt string         `json:"updated_at"`
}

type Skill struct {
	ID                     string         `json:"id"`
	Scope                  string         `json:"scope"`
	UserID                 sql.NullString `json:"user_id"`
	AgentID                sql.NullString `json:"agent_id"`
	Name                   string         `json:"name"`
	Description            string         `json:"description"`
	Status                 string         `json:"status"`
	DisableModelInvocation int64          `json:"disable_model_invocation"`
	Metadata               string         `json:"metadata"`
	CreatedAt              string         `json:"created_at"`
	UpdatedAt              string         `json:"updated_at"`
}

type SkillFile struct {
	SkillID string `json:"skill_id"`
	Path    string `json:"path"`
	Content string `json:"content"`
}

type VaultEntry struct {
	ID         string `json:"id"`
	UserID     string `json:"user_id"`
	Name       string `json:"name"`
	Ciphertext string `json:"ciphertext"`
	CreatedAt  string `json:"created_at"`
	UpdatedAt  string `json:"updated_at"`
}
