/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as STokenRouteImport } from './routes/s.$token'
import { Route as DocsSplatRouteImport } from './routes/docs/$'
import { Route as AppTasksRouteImport } from './routes/_app/tasks'
import { Route as AppSettingsRouteImport } from './routes/_app/settings'
import { Route as AppSessionsRouteImport } from './routes/_app/sessions'
import { Route as AppSchedulerRouteImport } from './routes/_app/scheduler'
import { Route as AppRecallyRouteImport } from './routes/_app/recally'
import { Route as AppAutomationsRouteImport } from './routes/_app/automations'
import { Route as AppAgentsRouteImport } from './routes/_app/agents'
import { Route as AppSettingsIndexRouteImport } from './routes/_app/settings/index'
import { Route as AppAgentsIndexRouteImport } from './routes/_app/agents.index'
import { Route as AppTasksTaskIdRouteImport } from './routes/_app/tasks.$taskId'
import { Route as AppSettingsUsersRouteImport } from './routes/_app/settings/users'
import { Route as AppSettingsSandboxRouteImport } from './routes/_app/settings/sandbox'
import { Route as AppSettingsProvidersRouteImport } from './routes/_app/settings/providers'
import { Route as AppSettingsPluginsRouteImport } from './routes/_app/settings/plugins'
import { Route as AppSettingsCredentialsRouteImport } from './routes/_app/settings/credentials'
import { Route as AppSettingsChannelsRouteImport } from './routes/_app/settings/channels'
import { Route as AppSettingsAgentsRouteImport } from './routes/_app/settings/agents'
import { Route as AppSettingsAccountRouteImport } from './routes/_app/settings/account'
import { Route as AppSettingsAboutRouteImport } from './routes/_app/settings/about'
import { Route as AppSessionsSplatRouteImport } from './routes/_app/sessions.$'
import { Route as AppAutomationsSplatRouteImport } from './routes/_app/automations.$'
import { Route as AppAgentsAgentIdRouteImport } from './routes/_app/agents.$agentId'
import { Route as AppAgentsAgentIdIndexRouteImport } from './routes/_app/agents.$agentId/index'
import { Route as AppSettingsAgentsAgentIdRouteImport } from './routes/_app/settings/agents.$agentId'
import { Route as AppAgentsAgentIdTasksIndexRouteImport } from './routes/_app/agents.$agentId/tasks/index'
import { Route as AppAgentsAgentIdSkillsIndexRouteImport } from './routes/_app/agents.$agentId/skills/index'
import { Route as AppAgentsAgentIdAutomationsIndexRouteImport } from './routes/_app/agents.$agentId/automations/index'
import { Route as AppSettingsAgentsAgentIdTabRouteImport } from './routes/_app/settings/agents.$agentId.$tab'
import { Route as AppAgentsAgentIdTasksNewRouteImport } from './routes/_app/agents.$agentId/tasks/new'
import { Route as AppAgentsAgentIdTasksTaskIdRouteImport } from './routes/_app/agents.$agentId/tasks/$taskId'
import { Route as AppAgentsAgentIdSkillsNewRouteImport } from './routes/_app/agents.$agentId/skills/new'
import { Route as AppAgentsAgentIdSkillsSkillIdRouteImport } from './routes/_app/agents.$agentId/skills/$skillId'
import { Route as AppAgentsAgentIdSessionsSessionIdRouteImport } from './routes/_app/agents.$agentId/sessions.$sessionId'
import { Route as AppAgentsAgentIdMemoriesSoulRouteImport } from './routes/_app/agents.$agentId/memories/soul'
import { Route as AppAgentsAgentIdMemoriesProfileRouteImport } from './routes/_app/agents.$agentId/memories/profile'
import { Route as AppAgentsAgentIdAutomationsNewRouteImport } from './routes/_app/agents.$agentId/automations/new'
import { Route as AppAgentsAgentIdAutomationsJobIdRouteImport } from './routes/_app/agents.$agentId/automations/$jobId'
import { Route as AppAgentsAgentIdProjectsProjectIdIndexRouteImport } from './routes/_app/agents.$agentId/projects.$projectId/index'
import { Route as AppAgentsAgentIdSkillsScopeSkillIdRouteImport } from './routes/_app/agents.$agentId/skills/$scope.$skillId'
import { Route as AppAgentsAgentIdAutomationsGoalsGoalIdRouteImport } from './routes/_app/agents.$agentId/automations/goals.$goalId'
import { Route as AppAgentsAgentIdAutomationsJobIdEditRouteImport } from './routes/_app/agents.$agentId/automations/$jobId.edit'
import { Route as AppAgentsAgentIdProjectsProjectIdSessionsSessionIdRouteImport } from './routes/_app/agents.$agentId/projects.$projectId/sessions.$sessionId'
import { Route as AppAgentsAgentIdAutomationsJobIdRunsRunIdRouteImport } from './routes/_app/agents.$agentId/automations/$jobId.runs.$runId'

const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/login.lazy').then((d) => d.Route))
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/_app.lazy').then((d) => d.Route))
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const STokenRoute = STokenRouteImport.update({
  id: '/s/$token',
  path: '/s/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsSplatRoute = DocsSplatRouteImport.update({
  id: '/docs/$',
  path: '/docs/$',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/docs/$.lazy').then((d) => d.Route))
const AppTasksRoute = AppTasksRouteImport.update({
  id: '/tasks',
  path: '/tasks',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any).lazy(() => import('./routes/_app/settings.lazy').then((d) => d.Route))
const AppSessionsRoute = AppSessionsRouteImport.update({
  id: '/sessions',
  path: '/sessions',
  getParentRoute: () => AppRoute,
} as any)
const AppSchedulerRoute = AppSchedulerRouteImport.update({
  id: '/scheduler',
  path: '/scheduler',
  getParentRoute: () => AppRoute,
} as any).lazy(() =>
  import('./routes/_app/scheduler.lazy').then((d) => d.Route),
)
const AppRecallyRoute = AppRecallyRouteImport.update({
  id: '/recally',
  path: '/recally',
  getParentRoute: () => AppRoute,
} as any).lazy(() => import('./routes/_app/recally.lazy').then((d) => d.Route))
const AppAutomationsRoute = AppAutomationsRouteImport.update({
  id: '/automations',
  path: '/automations',
  getParentRoute: () => AppRoute,
} as any)
const AppAgentsRoute = AppAgentsRouteImport.update({
  id: '/agents',
  path: '/agents',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsIndexRoute = AppSettingsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppSettingsRoute,
} as any)
const AppAgentsIndexRoute = AppAgentsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppAgentsRoute,
} as any)
const AppTasksTaskIdRoute = AppTasksTaskIdRouteImport.update({
  id: '/$taskId',
  path: '/$taskId',
  getParentRoute: () => AppTasksRoute,
} as any)
const AppSettingsUsersRoute = AppSettingsUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AppSettingsRoute,
} as any).lazy(() =>
  import('./routes/_app/settings/users.lazy').then((d) => d.Route),
)
const AppSettingsSandboxRoute = AppSettingsSandboxRouteImport.update({
  id: '/sandbox',
  path: '/sandbox',
  getParentRoute: () => AppSettingsRoute,
} as any).lazy(() =>
  import('./routes/_app/settings/sandbox.lazy').then((d) => d.Route),
)
const AppSettingsProvidersRoute = AppSettingsProvidersRouteImport.update({
  id: '/providers',
  path: '/providers',
  getParentRoute: () => AppSettingsRoute,
} as any).lazy(() =>
  import('./routes/_app/settings/providers.lazy').then((d) => d.Route),
)
const AppSettingsPluginsRoute = AppSettingsPluginsRouteImport.update({
  id: '/plugins',
  path: '/plugins',
  getParentRoute: () => AppSettingsRoute,
} as any).lazy(() =>
  import('./routes/_app/settings/plugins.lazy').then((d) => d.Route),
)
const AppSettingsCredentialsRoute = AppSettingsCredentialsRouteImport.update({
  id: '/credentials',
  path: '/credentials',
  getParentRoute: () => AppSettingsRoute,
} as any).lazy(() =>
  import('./routes/_app/settings/credentials.lazy').then((d) => d.Route),
)
const AppSettingsChannelsRoute = AppSettingsChannelsRouteImport.update({
  id: '/channels',
  path: '/channels',
  getParentRoute: () => AppSettingsRoute,
} as any).lazy(() =>
  import('./routes/_app/settings/channels.lazy').then((d) => d.Route),
)
const AppSettingsAgentsRoute = AppSettingsAgentsRouteImport.update({
  id: '/agents',
  path: '/agents',
  getParentRoute: () => AppSettingsRoute,
} as any).lazy(() =>
  import('./routes/_app/settings/agents.lazy').then((d) => d.Route),
)
const AppSettingsAccountRoute = AppSettingsAccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => AppSettingsRoute,
} as any).lazy(() =>
  import('./routes/_app/settings/account.lazy').then((d) => d.Route),
)
const AppSettingsAboutRoute = AppSettingsAboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => AppSettingsRoute,
} as any).lazy(() =>
  import('./routes/_app/settings/about.lazy').then((d) => d.Route),
)
const AppSessionsSplatRoute = AppSessionsSplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => AppSessionsRoute,
} as any)
const AppAutomationsSplatRoute = AppAutomationsSplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => AppAutomationsRoute,
} as any)
const AppAgentsAgentIdRoute = AppAgentsAgentIdRouteImport.update({
  id: '/$agentId',
  path: '/$agentId',
  getParentRoute: () => AppAgentsRoute,
} as any).lazy(() =>
  import('./routes/_app/agents.$agentId.lazy').then((d) => d.Route),
)
const AppAgentsAgentIdIndexRoute = AppAgentsAgentIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppAgentsAgentIdRoute,
} as any).lazy(() =>
  import('./routes/_app/agents.$agentId/index.lazy').then((d) => d.Route),
)
const AppSettingsAgentsAgentIdRoute =
  AppSettingsAgentsAgentIdRouteImport.update({
    id: '/$agentId',
    path: '/$agentId',
    getParentRoute: () => AppSettingsAgentsRoute,
  } as any).lazy(() =>
    import('./routes/_app/settings/agents.$agentId.lazy').then((d) => d.Route),
  )
const AppAgentsAgentIdTasksIndexRoute =
  AppAgentsAgentIdTasksIndexRouteImport.update({
    id: '/tasks/',
    path: '/tasks/',
    getParentRoute: () => AppAgentsAgentIdRoute,
  } as any).lazy(() =>
    import('./routes/_app/agents.$agentId/tasks/index.lazy').then(
      (d) => d.Route,
    ),
  )
const AppAgentsAgentIdSkillsIndexRoute =
  AppAgentsAgentIdSkillsIndexRouteImport.update({
    id: '/skills/',
    path: '/skills/',
    getParentRoute: () => AppAgentsAgentIdRoute,
  } as any).lazy(() =>
    import('./routes/_app/agents.$agentId/skills/index.lazy').then(
      (d) => d.Route,
    ),
  )
const AppAgentsAgentIdAutomationsIndexRoute =
  AppAgentsAgentIdAutomationsIndexRouteImport.update({
    id: '/automations/',
    path: '/automations/',
    getParentRoute: () => AppAgentsAgentIdRoute,
  } as any).lazy(() =>
    import('./routes/_app/agents.$agentId/automations/index.lazy').then(
      (d) => d.Route,
    ),
  )
const AppSettingsAgentsAgentIdTabRoute =
  AppSettingsAgentsAgentIdTabRouteImport.update({
    id: '/$tab',
    path: '/$tab',
    getParentRoute: () => AppSettingsAgentsAgentIdRoute,
  } as any).lazy(() =>
    import('./routes/_app/settings/agents.$agentId.$tab.lazy').then(
      (d) => d.Route,
    ),
  )
const AppAgentsAgentIdTasksNewRoute =
  AppAgentsAgentIdTasksNewRouteImport.update({
    id: '/tasks/new',
    path: '/tasks/new',
    getParentRoute: () => AppAgentsAgentIdRoute,
  } as any).lazy(() =>
    import('./routes/_app/agents.$agentId/tasks/new.lazy').then((d) => d.Route),
  )
const AppAgentsAgentIdTasksTaskIdRoute =
  AppAgentsAgentIdTasksTaskIdRouteImport.update({
    id: '/tasks/$taskId',
    path: '/tasks/$taskId',
    getParentRoute: () => AppAgentsAgentIdRoute,
  } as any).lazy(() =>
    import('./routes/_app/agents.$agentId/tasks/$taskId.lazy').then(
      (d) => d.Route,
    ),
  )
const AppAgentsAgentIdSkillsNewRoute =
  AppAgentsAgentIdSkillsNewRouteImport.update({
    id: '/skills/new',
    path: '/skills/new',
    getParentRoute: () => AppAgentsAgentIdRoute,
  } as any).lazy(() =>
    import('./routes/_app/agents.$agentId/skills/new.lazy').then(
      (d) => d.Route,
    ),
  )
const AppAgentsAgentIdSkillsSkillIdRoute =
  AppAgentsAgentIdSkillsSkillIdRouteImport.update({
    id: '/skills/$skillId',
    path: '/skills/$skillId',
    getParentRoute: () => AppAgentsAgentIdRoute,
  } as any).lazy(() =>
    import('./routes/_app/agents.$agentId/skills/$skillId.lazy').then(
      (d) => d.Route,
    ),
  )
const AppAgentsAgentIdSessionsSessionIdRoute =
  AppAgentsAgentIdSessionsSessionIdRouteImport.update({
    id: '/sessions/$sessionId',
    path: '/sessions/$sessionId',
    getParentRoute: () => AppAgentsAgentIdRoute,
  } as any).lazy(() =>
    import('./routes/_app/agents.$agentId/sessions.$sessionId.lazy').then(
      (d) => d.Route,
    ),
  )
const AppAgentsAgentIdMemoriesSoulRoute =
  AppAgentsAgentIdMemoriesSoulRouteImport.update({
    id: '/memories/soul',
    path: '/memories/soul',
    getParentRoute: () => AppAgentsAgentIdRoute,
  } as any).lazy(() =>
    import('./routes/_app/agents.$agentId/memories/soul.lazy').then(
      (d) => d.Route,
    ),
  )
const AppAgentsAgentIdMemoriesProfileRoute =
  AppAgentsAgentIdMemoriesProfileRouteImport.update({
    id: '/memories/profile',
    path: '/memories/profile',
    getParentRoute: () => AppAgentsAgentIdRoute,
  } as any).lazy(() =>
    import('./routes/_app/agents.$agentId/memories/profile.lazy').then(
      (d) => d.Route,
    ),
  )
const AppAgentsAgentIdAutomationsNewRoute =
  AppAgentsAgentIdAutomationsNewRouteImport.update({
    id: '/automations/new',
    path: '/automations/new',
    getParentRoute: () => AppAgentsAgentIdRoute,
  } as any).lazy(() =>
    import('./routes/_app/agents.$agentId/automations/new.lazy').then(
      (d) => d.Route,
    ),
  )
const AppAgentsAgentIdAutomationsJobIdRoute =
  AppAgentsAgentIdAutomationsJobIdRouteImport.update({
    id: '/automations/$jobId',
    path: '/automations/$jobId',
    getParentRoute: () => AppAgentsAgentIdRoute,
  } as any).lazy(() =>
    import('./routes/_app/agents.$agentId/automations/$jobId.lazy').then(
      (d) => d.Route,
    ),
  )
const AppAgentsAgentIdProjectsProjectIdIndexRoute =
  AppAgentsAgentIdProjectsProjectIdIndexRouteImport.update({
    id: '/projects/$projectId/',
    path: '/projects/$projectId/',
    getParentRoute: () => AppAgentsAgentIdRoute,
  } as any).lazy(() =>
    import('./routes/_app/agents.$agentId/projects.$projectId/index.lazy').then(
      (d) => d.Route,
    ),
  )
const AppAgentsAgentIdSkillsScopeSkillIdRoute =
  AppAgentsAgentIdSkillsScopeSkillIdRouteImport.update({
    id: '/skills/$scope/$skillId',
    path: '/skills/$scope/$skillId',
    getParentRoute: () => AppAgentsAgentIdRoute,
  } as any).lazy(() =>
    import('./routes/_app/agents.$agentId/skills/$scope.$skillId.lazy').then(
      (d) => d.Route,
    ),
  )
const AppAgentsAgentIdAutomationsGoalsGoalIdRoute =
  AppAgentsAgentIdAutomationsGoalsGoalIdRouteImport.update({
    id: '/automations/goals/$goalId',
    path: '/automations/goals/$goalId',
    getParentRoute: () => AppAgentsAgentIdRoute,
  } as any).lazy(() =>
    import('./routes/_app/agents.$agentId/automations/goals.$goalId.lazy').then(
      (d) => d.Route,
    ),
  )
const AppAgentsAgentIdAutomationsJobIdEditRoute =
  AppAgentsAgentIdAutomationsJobIdEditRouteImport.update({
    id: '/edit',
    path: '/edit',
    getParentRoute: () => AppAgentsAgentIdAutomationsJobIdRoute,
  } as any).lazy(() =>
    import('./routes/_app/agents.$agentId/automations/$jobId.edit.lazy').then(
      (d) => d.Route,
    ),
  )
const AppAgentsAgentIdProjectsProjectIdSessionsSessionIdRoute =
  AppAgentsAgentIdProjectsProjectIdSessionsSessionIdRouteImport.update({
    id: '/projects/$projectId/sessions/$sessionId',
    path: '/projects/$projectId/sessions/$sessionId',
    getParentRoute: () => AppAgentsAgentIdRoute,
  } as any).lazy(() =>
    import('./routes/_app/agents.$agentId/projects.$projectId/sessions.$sessionId.lazy').then(
      (d) => d.Route,
    ),
  )
const AppAgentsAgentIdAutomationsJobIdRunsRunIdRoute =
  AppAgentsAgentIdAutomationsJobIdRunsRunIdRouteImport.update({
    id: '/runs/$runId',
    path: '/runs/$runId',
    getParentRoute: () => AppAgentsAgentIdAutomationsJobIdRoute,
  } as any).lazy(() =>
    import('./routes/_app/agents.$agentId/automations/$jobId.runs.$runId.lazy').then(
      (d) => d.Route,
    ),
  )

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/profile': typeof ProfileRoute
  '/agents': typeof AppAgentsRouteWithChildren
  '/automations': typeof AppAutomationsRouteWithChildren
  '/recally': typeof AppRecallyRoute
  '/scheduler': typeof AppSchedulerRoute
  '/sessions': typeof AppSessionsRouteWithChildren
  '/settings': typeof AppSettingsRouteWithChildren
  '/tasks': typeof AppTasksRouteWithChildren
  '/docs/$': typeof DocsSplatRoute
  '/s/$token': typeof STokenRoute
  '/agents/$agentId': typeof AppAgentsAgentIdRouteWithChildren
  '/automations/$': typeof AppAutomationsSplatRoute
  '/sessions/$': typeof AppSessionsSplatRoute
  '/settings/about': typeof AppSettingsAboutRoute
  '/settings/account': typeof AppSettingsAccountRoute
  '/settings/agents': typeof AppSettingsAgentsRouteWithChildren
  '/settings/channels': typeof AppSettingsChannelsRoute
  '/settings/credentials': typeof AppSettingsCredentialsRoute
  '/settings/plugins': typeof AppSettingsPluginsRoute
  '/settings/providers': typeof AppSettingsProvidersRoute
  '/settings/sandbox': typeof AppSettingsSandboxRoute
  '/settings/users': typeof AppSettingsUsersRoute
  '/tasks/$taskId': typeof AppTasksTaskIdRoute
  '/agents/': typeof AppAgentsIndexRoute
  '/settings/': typeof AppSettingsIndexRoute
  '/settings/agents/$agentId': typeof AppSettingsAgentsAgentIdRouteWithChildren
  '/agents/$agentId/': typeof AppAgentsAgentIdIndexRoute
  '/agents/$agentId/automations/$jobId': typeof AppAgentsAgentIdAutomationsJobIdRouteWithChildren
  '/agents/$agentId/automations/new': typeof AppAgentsAgentIdAutomationsNewRoute
  '/agents/$agentId/memories/profile': typeof AppAgentsAgentIdMemoriesProfileRoute
  '/agents/$agentId/memories/soul': typeof AppAgentsAgentIdMemoriesSoulRoute
  '/agents/$agentId/sessions/$sessionId': typeof AppAgentsAgentIdSessionsSessionIdRoute
  '/agents/$agentId/skills/$skillId': typeof AppAgentsAgentIdSkillsSkillIdRoute
  '/agents/$agentId/skills/new': typeof AppAgentsAgentIdSkillsNewRoute
  '/agents/$agentId/tasks/$taskId': typeof AppAgentsAgentIdTasksTaskIdRoute
  '/agents/$agentId/tasks/new': typeof AppAgentsAgentIdTasksNewRoute
  '/settings/agents/$agentId/$tab': typeof AppSettingsAgentsAgentIdTabRoute
  '/agents/$agentId/automations/': typeof AppAgentsAgentIdAutomationsIndexRoute
  '/agents/$agentId/skills/': typeof AppAgentsAgentIdSkillsIndexRoute
  '/agents/$agentId/tasks/': typeof AppAgentsAgentIdTasksIndexRoute
  '/agents/$agentId/automations/$jobId/edit': typeof AppAgentsAgentIdAutomationsJobIdEditRoute
  '/agents/$agentId/automations/goals/$goalId': typeof AppAgentsAgentIdAutomationsGoalsGoalIdRoute
  '/agents/$agentId/skills/$scope/$skillId': typeof AppAgentsAgentIdSkillsScopeSkillIdRoute
  '/agents/$agentId/projects/$projectId/': typeof AppAgentsAgentIdProjectsProjectIdIndexRoute
  '/agents/$agentId/automations/$jobId/runs/$runId': typeof AppAgentsAgentIdAutomationsJobIdRunsRunIdRoute
  '/agents/$agentId/projects/$projectId/sessions/$sessionId': typeof AppAgentsAgentIdProjectsProjectIdSessionsSessionIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/profile': typeof ProfileRoute
  '/automations': typeof AppAutomationsRouteWithChildren
  '/recally': typeof AppRecallyRoute
  '/scheduler': typeof AppSchedulerRoute
  '/sessions': typeof AppSessionsRouteWithChildren
  '/tasks': typeof AppTasksRouteWithChildren
  '/docs/$': typeof DocsSplatRoute
  '/s/$token': typeof STokenRoute
  '/automations/$': typeof AppAutomationsSplatRoute
  '/sessions/$': typeof AppSessionsSplatRoute
  '/settings/about': typeof AppSettingsAboutRoute
  '/settings/account': typeof AppSettingsAccountRoute
  '/settings/agents': typeof AppSettingsAgentsRouteWithChildren
  '/settings/channels': typeof AppSettingsChannelsRoute
  '/settings/credentials': typeof AppSettingsCredentialsRoute
  '/settings/plugins': typeof AppSettingsPluginsRoute
  '/settings/providers': typeof AppSettingsProvidersRoute
  '/settings/sandbox': typeof AppSettingsSandboxRoute
  '/settings/users': typeof AppSettingsUsersRoute
  '/tasks/$taskId': typeof AppTasksTaskIdRoute
  '/agents': typeof AppAgentsIndexRoute
  '/settings': typeof AppSettingsIndexRoute
  '/settings/agents/$agentId': typeof AppSettingsAgentsAgentIdRouteWithChildren
  '/agents/$agentId': typeof AppAgentsAgentIdIndexRoute
  '/agents/$agentId/automations/$jobId': typeof AppAgentsAgentIdAutomationsJobIdRouteWithChildren
  '/agents/$agentId/automations/new': typeof AppAgentsAgentIdAutomationsNewRoute
  '/agents/$agentId/memories/profile': typeof AppAgentsAgentIdMemoriesProfileRoute
  '/agents/$agentId/memories/soul': typeof AppAgentsAgentIdMemoriesSoulRoute
  '/agents/$agentId/sessions/$sessionId': typeof AppAgentsAgentIdSessionsSessionIdRoute
  '/agents/$agentId/skills/$skillId': typeof AppAgentsAgentIdSkillsSkillIdRoute
  '/agents/$agentId/skills/new': typeof AppAgentsAgentIdSkillsNewRoute
  '/agents/$agentId/tasks/$taskId': typeof AppAgentsAgentIdTasksTaskIdRoute
  '/agents/$agentId/tasks/new': typeof AppAgentsAgentIdTasksNewRoute
  '/settings/agents/$agentId/$tab': typeof AppSettingsAgentsAgentIdTabRoute
  '/agents/$agentId/automations': typeof AppAgentsAgentIdAutomationsIndexRoute
  '/agents/$agentId/skills': typeof AppAgentsAgentIdSkillsIndexRoute
  '/agents/$agentId/tasks': typeof AppAgentsAgentIdTasksIndexRoute
  '/agents/$agentId/automations/$jobId/edit': typeof AppAgentsAgentIdAutomationsJobIdEditRoute
  '/agents/$agentId/automations/goals/$goalId': typeof AppAgentsAgentIdAutomationsGoalsGoalIdRoute
  '/agents/$agentId/skills/$scope/$skillId': typeof AppAgentsAgentIdSkillsScopeSkillIdRoute
  '/agents/$agentId/projects/$projectId': typeof AppAgentsAgentIdProjectsProjectIdIndexRoute
  '/agents/$agentId/automations/$jobId/runs/$runId': typeof AppAgentsAgentIdAutomationsJobIdRunsRunIdRoute
  '/agents/$agentId/projects/$projectId/sessions/$sessionId': typeof AppAgentsAgentIdProjectsProjectIdSessionsSessionIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/profile': typeof ProfileRoute
  '/_app/agents': typeof AppAgentsRouteWithChildren
  '/_app/automations': typeof AppAutomationsRouteWithChildren
  '/_app/recally': typeof AppRecallyRoute
  '/_app/scheduler': typeof AppSchedulerRoute
  '/_app/sessions': typeof AppSessionsRouteWithChildren
  '/_app/settings': typeof AppSettingsRouteWithChildren
  '/_app/tasks': typeof AppTasksRouteWithChildren
  '/docs/$': typeof DocsSplatRoute
  '/s/$token': typeof STokenRoute
  '/_app/agents/$agentId': typeof AppAgentsAgentIdRouteWithChildren
  '/_app/automations/$': typeof AppAutomationsSplatRoute
  '/_app/sessions/$': typeof AppSessionsSplatRoute
  '/_app/settings/about': typeof AppSettingsAboutRoute
  '/_app/settings/account': typeof AppSettingsAccountRoute
  '/_app/settings/agents': typeof AppSettingsAgentsRouteWithChildren
  '/_app/settings/channels': typeof AppSettingsChannelsRoute
  '/_app/settings/credentials': typeof AppSettingsCredentialsRoute
  '/_app/settings/plugins': typeof AppSettingsPluginsRoute
  '/_app/settings/providers': typeof AppSettingsProvidersRoute
  '/_app/settings/sandbox': typeof AppSettingsSandboxRoute
  '/_app/settings/users': typeof AppSettingsUsersRoute
  '/_app/tasks/$taskId': typeof AppTasksTaskIdRoute
  '/_app/agents/': typeof AppAgentsIndexRoute
  '/_app/settings/': typeof AppSettingsIndexRoute
  '/_app/settings/agents/$agentId': typeof AppSettingsAgentsAgentIdRouteWithChildren
  '/_app/agents/$agentId/': typeof AppAgentsAgentIdIndexRoute
  '/_app/agents/$agentId/automations/$jobId': typeof AppAgentsAgentIdAutomationsJobIdRouteWithChildren
  '/_app/agents/$agentId/automations/new': typeof AppAgentsAgentIdAutomationsNewRoute
  '/_app/agents/$agentId/memories/profile': typeof AppAgentsAgentIdMemoriesProfileRoute
  '/_app/agents/$agentId/memories/soul': typeof AppAgentsAgentIdMemoriesSoulRoute
  '/_app/agents/$agentId/sessions/$sessionId': typeof AppAgentsAgentIdSessionsSessionIdRoute
  '/_app/agents/$agentId/skills/$skillId': typeof AppAgentsAgentIdSkillsSkillIdRoute
  '/_app/agents/$agentId/skills/new': typeof AppAgentsAgentIdSkillsNewRoute
  '/_app/agents/$agentId/tasks/$taskId': typeof AppAgentsAgentIdTasksTaskIdRoute
  '/_app/agents/$agentId/tasks/new': typeof AppAgentsAgentIdTasksNewRoute
  '/_app/settings/agents/$agentId/$tab': typeof AppSettingsAgentsAgentIdTabRoute
  '/_app/agents/$agentId/automations/': typeof AppAgentsAgentIdAutomationsIndexRoute
  '/_app/agents/$agentId/skills/': typeof AppAgentsAgentIdSkillsIndexRoute
  '/_app/agents/$agentId/tasks/': typeof AppAgentsAgentIdTasksIndexRoute
  '/_app/agents/$agentId/automations/$jobId/edit': typeof AppAgentsAgentIdAutomationsJobIdEditRoute
  '/_app/agents/$agentId/automations/goals/$goalId': typeof AppAgentsAgentIdAutomationsGoalsGoalIdRoute
  '/_app/agents/$agentId/skills/$scope/$skillId': typeof AppAgentsAgentIdSkillsScopeSkillIdRoute
  '/_app/agents/$agentId/projects/$projectId/': typeof AppAgentsAgentIdProjectsProjectIdIndexRoute
  '/_app/agents/$agentId/automations/$jobId/runs/$runId': typeof AppAgentsAgentIdAutomationsJobIdRunsRunIdRoute
  '/_app/agents/$agentId/projects/$projectId/sessions/$sessionId': typeof AppAgentsAgentIdProjectsProjectIdSessionsSessionIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/profile'
    | '/agents'
    | '/automations'
    | '/recally'
    | '/scheduler'
    | '/sessions'
    | '/settings'
    | '/tasks'
    | '/docs/$'
    | '/s/$token'
    | '/agents/$agentId'
    | '/automations/$'
    | '/sessions/$'
    | '/settings/about'
    | '/settings/account'
    | '/settings/agents'
    | '/settings/channels'
    | '/settings/credentials'
    | '/settings/plugins'
    | '/settings/providers'
    | '/settings/sandbox'
    | '/settings/users'
    | '/tasks/$taskId'
    | '/agents/'
    | '/settings/'
    | '/settings/agents/$agentId'
    | '/agents/$agentId/'
    | '/agents/$agentId/automations/$jobId'
    | '/agents/$agentId/automations/new'
    | '/agents/$agentId/memories/profile'
    | '/agents/$agentId/memories/soul'
    | '/agents/$agentId/sessions/$sessionId'
    | '/agents/$agentId/skills/$skillId'
    | '/agents/$agentId/skills/new'
    | '/agents/$agentId/tasks/$taskId'
    | '/agents/$agentId/tasks/new'
    | '/settings/agents/$agentId/$tab'
    | '/agents/$agentId/automations/'
    | '/agents/$agentId/skills/'
    | '/agents/$agentId/tasks/'
    | '/agents/$agentId/automations/$jobId/edit'
    | '/agents/$agentId/automations/goals/$goalId'
    | '/agents/$agentId/skills/$scope/$skillId'
    | '/agents/$agentId/projects/$projectId/'
    | '/agents/$agentId/automations/$jobId/runs/$runId'
    | '/agents/$agentId/projects/$projectId/sessions/$sessionId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/profile'
    | '/automations'
    | '/recally'
    | '/scheduler'
    | '/sessions'
    | '/tasks'
    | '/docs/$'
    | '/s/$token'
    | '/automations/$'
    | '/sessions/$'
    | '/settings/about'
    | '/settings/account'
    | '/settings/agents'
    | '/settings/channels'
    | '/settings/credentials'
    | '/settings/plugins'
    | '/settings/providers'
    | '/settings/sandbox'
    | '/settings/users'
    | '/tasks/$taskId'
    | '/agents'
    | '/settings'
    | '/settings/agents/$agentId'
    | '/agents/$agentId'
    | '/agents/$agentId/automations/$jobId'
    | '/agents/$agentId/automations/new'
    | '/agents/$agentId/memories/profile'
    | '/agents/$agentId/memories/soul'
    | '/agents/$agentId/sessions/$sessionId'
    | '/agents/$agentId/skills/$skillId'
    | '/agents/$agentId/skills/new'
    | '/agents/$agentId/tasks/$taskId'
    | '/agents/$agentId/tasks/new'
    | '/settings/agents/$agentId/$tab'
    | '/agents/$agentId/automations'
    | '/agents/$agentId/skills'
    | '/agents/$agentId/tasks'
    | '/agents/$agentId/automations/$jobId/edit'
    | '/agents/$agentId/automations/goals/$goalId'
    | '/agents/$agentId/skills/$scope/$skillId'
    | '/agents/$agentId/projects/$projectId'
    | '/agents/$agentId/automations/$jobId/runs/$runId'
    | '/agents/$agentId/projects/$projectId/sessions/$sessionId'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/login'
    | '/profile'
    | '/_app/agents'
    | '/_app/automations'
    | '/_app/recally'
    | '/_app/scheduler'
    | '/_app/sessions'
    | '/_app/settings'
    | '/_app/tasks'
    | '/docs/$'
    | '/s/$token'
    | '/_app/agents/$agentId'
    | '/_app/automations/$'
    | '/_app/sessions/$'
    | '/_app/settings/about'
    | '/_app/settings/account'
    | '/_app/settings/agents'
    | '/_app/settings/channels'
    | '/_app/settings/credentials'
    | '/_app/settings/plugins'
    | '/_app/settings/providers'
    | '/_app/settings/sandbox'
    | '/_app/settings/users'
    | '/_app/tasks/$taskId'
    | '/_app/agents/'
    | '/_app/settings/'
    | '/_app/settings/agents/$agentId'
    | '/_app/agents/$agentId/'
    | '/_app/agents/$agentId/automations/$jobId'
    | '/_app/agents/$agentId/automations/new'
    | '/_app/agents/$agentId/memories/profile'
    | '/_app/agents/$agentId/memories/soul'
    | '/_app/agents/$agentId/sessions/$sessionId'
    | '/_app/agents/$agentId/skills/$skillId'
    | '/_app/agents/$agentId/skills/new'
    | '/_app/agents/$agentId/tasks/$taskId'
    | '/_app/agents/$agentId/tasks/new'
    | '/_app/settings/agents/$agentId/$tab'
    | '/_app/agents/$agentId/automations/'
    | '/_app/agents/$agentId/skills/'
    | '/_app/agents/$agentId/tasks/'
    | '/_app/agents/$agentId/automations/$jobId/edit'
    | '/_app/agents/$agentId/automations/goals/$goalId'
    | '/_app/agents/$agentId/skills/$scope/$skillId'
    | '/_app/agents/$agentId/projects/$projectId/'
    | '/_app/agents/$agentId/automations/$jobId/runs/$runId'
    | '/_app/agents/$agentId/projects/$projectId/sessions/$sessionId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
  ProfileRoute: typeof ProfileRoute
  DocsSplatRoute: typeof DocsSplatRoute
  STokenRoute: typeof STokenRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/s/$token': {
      id: '/s/$token'
      path: '/s/$token'
      fullPath: '/s/$token'
      preLoaderRoute: typeof STokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/$': {
      id: '/docs/$'
      path: '/docs/$'
      fullPath: '/docs/$'
      preLoaderRoute: typeof DocsSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/tasks': {
      id: '/_app/tasks'
      path: '/tasks'
      fullPath: '/tasks'
      preLoaderRoute: typeof AppTasksRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/sessions': {
      id: '/_app/sessions'
      path: '/sessions'
      fullPath: '/sessions'
      preLoaderRoute: typeof AppSessionsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/scheduler': {
      id: '/_app/scheduler'
      path: '/scheduler'
      fullPath: '/scheduler'
      preLoaderRoute: typeof AppSchedulerRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/recally': {
      id: '/_app/recally'
      path: '/recally'
      fullPath: '/recally'
      preLoaderRoute: typeof AppRecallyRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/automations': {
      id: '/_app/automations'
      path: '/automations'
      fullPath: '/automations'
      preLoaderRoute: typeof AppAutomationsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/agents': {
      id: '/_app/agents'
      path: '/agents'
      fullPath: '/agents'
      preLoaderRoute: typeof AppAgentsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings/': {
      id: '/_app/settings/'
      path: '/'
      fullPath: '/settings/'
      preLoaderRoute: typeof AppSettingsIndexRouteImport
      parentRoute: typeof AppSettingsRoute
    }
    '/_app/agents/': {
      id: '/_app/agents/'
      path: '/'
      fullPath: '/agents/'
      preLoaderRoute: typeof AppAgentsIndexRouteImport
      parentRoute: typeof AppAgentsRoute
    }
    '/_app/tasks/$taskId': {
      id: '/_app/tasks/$taskId'
      path: '/$taskId'
      fullPath: '/tasks/$taskId'
      preLoaderRoute: typeof AppTasksTaskIdRouteImport
      parentRoute: typeof AppTasksRoute
    }
    '/_app/settings/users': {
      id: '/_app/settings/users'
      path: '/users'
      fullPath: '/settings/users'
      preLoaderRoute: typeof AppSettingsUsersRouteImport
      parentRoute: typeof AppSettingsRoute
    }
    '/_app/settings/sandbox': {
      id: '/_app/settings/sandbox'
      path: '/sandbox'
      fullPath: '/settings/sandbox'
      preLoaderRoute: typeof AppSettingsSandboxRouteImport
      parentRoute: typeof AppSettingsRoute
    }
    '/_app/settings/providers': {
      id: '/_app/settings/providers'
      path: '/providers'
      fullPath: '/settings/providers'
      preLoaderRoute: typeof AppSettingsProvidersRouteImport
      parentRoute: typeof AppSettingsRoute
    }
    '/_app/settings/plugins': {
      id: '/_app/settings/plugins'
      path: '/plugins'
      fullPath: '/settings/plugins'
      preLoaderRoute: typeof AppSettingsPluginsRouteImport
      parentRoute: typeof AppSettingsRoute
    }
    '/_app/settings/credentials': {
      id: '/_app/settings/credentials'
      path: '/credentials'
      fullPath: '/settings/credentials'
      preLoaderRoute: typeof AppSettingsCredentialsRouteImport
      parentRoute: typeof AppSettingsRoute
    }
    '/_app/settings/channels': {
      id: '/_app/settings/channels'
      path: '/channels'
      fullPath: '/settings/channels'
      preLoaderRoute: typeof AppSettingsChannelsRouteImport
      parentRoute: typeof AppSettingsRoute
    }
    '/_app/settings/agents': {
      id: '/_app/settings/agents'
      path: '/agents'
      fullPath: '/settings/agents'
      preLoaderRoute: typeof AppSettingsAgentsRouteImport
      parentRoute: typeof AppSettingsRoute
    }
    '/_app/settings/account': {
      id: '/_app/settings/account'
      path: '/account'
      fullPath: '/settings/account'
      preLoaderRoute: typeof AppSettingsAccountRouteImport
      parentRoute: typeof AppSettingsRoute
    }
    '/_app/settings/about': {
      id: '/_app/settings/about'
      path: '/about'
      fullPath: '/settings/about'
      preLoaderRoute: typeof AppSettingsAboutRouteImport
      parentRoute: typeof AppSettingsRoute
    }
    '/_app/sessions/$': {
      id: '/_app/sessions/$'
      path: '/$'
      fullPath: '/sessions/$'
      preLoaderRoute: typeof AppSessionsSplatRouteImport
      parentRoute: typeof AppSessionsRoute
    }
    '/_app/automations/$': {
      id: '/_app/automations/$'
      path: '/$'
      fullPath: '/automations/$'
      preLoaderRoute: typeof AppAutomationsSplatRouteImport
      parentRoute: typeof AppAutomationsRoute
    }
    '/_app/agents/$agentId': {
      id: '/_app/agents/$agentId'
      path: '/$agentId'
      fullPath: '/agents/$agentId'
      preLoaderRoute: typeof AppAgentsAgentIdRouteImport
      parentRoute: typeof AppAgentsRoute
    }
    '/_app/agents/$agentId/': {
      id: '/_app/agents/$agentId/'
      path: '/'
      fullPath: '/agents/$agentId/'
      preLoaderRoute: typeof AppAgentsAgentIdIndexRouteImport
      parentRoute: typeof AppAgentsAgentIdRoute
    }
    '/_app/settings/agents/$agentId': {
      id: '/_app/settings/agents/$agentId'
      path: '/$agentId'
      fullPath: '/settings/agents/$agentId'
      preLoaderRoute: typeof AppSettingsAgentsAgentIdRouteImport
      parentRoute: typeof AppSettingsAgentsRoute
    }
    '/_app/agents/$agentId/tasks/': {
      id: '/_app/agents/$agentId/tasks/'
      path: '/tasks'
      fullPath: '/agents/$agentId/tasks/'
      preLoaderRoute: typeof AppAgentsAgentIdTasksIndexRouteImport
      parentRoute: typeof AppAgentsAgentIdRoute
    }
    '/_app/agents/$agentId/skills/': {
      id: '/_app/agents/$agentId/skills/'
      path: '/skills'
      fullPath: '/agents/$agentId/skills/'
      preLoaderRoute: typeof AppAgentsAgentIdSkillsIndexRouteImport
      parentRoute: typeof AppAgentsAgentIdRoute
    }
    '/_app/agents/$agentId/automations/': {
      id: '/_app/agents/$agentId/automations/'
      path: '/automations'
      fullPath: '/agents/$agentId/automations/'
      preLoaderRoute: typeof AppAgentsAgentIdAutomationsIndexRouteImport
      parentRoute: typeof AppAgentsAgentIdRoute
    }
    '/_app/settings/agents/$agentId/$tab': {
      id: '/_app/settings/agents/$agentId/$tab'
      path: '/$tab'
      fullPath: '/settings/agents/$agentId/$tab'
      preLoaderRoute: typeof AppSettingsAgentsAgentIdTabRouteImport
      parentRoute: typeof AppSettingsAgentsAgentIdRoute
    }
    '/_app/agents/$agentId/tasks/new': {
      id: '/_app/agents/$agentId/tasks/new'
      path: '/tasks/new'
      fullPath: '/agents/$agentId/tasks/new'
      preLoaderRoute: typeof AppAgentsAgentIdTasksNewRouteImport
      parentRoute: typeof AppAgentsAgentIdRoute
    }
    '/_app/agents/$agentId/tasks/$taskId': {
      id: '/_app/agents/$agentId/tasks/$taskId'
      path: '/tasks/$taskId'
      fullPath: '/agents/$agentId/tasks/$taskId'
      preLoaderRoute: typeof AppAgentsAgentIdTasksTaskIdRouteImport
      parentRoute: typeof AppAgentsAgentIdRoute
    }
    '/_app/agents/$agentId/skills/new': {
      id: '/_app/agents/$agentId/skills/new'
      path: '/skills/new'
      fullPath: '/agents/$agentId/skills/new'
      preLoaderRoute: typeof AppAgentsAgentIdSkillsNewRouteImport
      parentRoute: typeof AppAgentsAgentIdRoute
    }
    '/_app/agents/$agentId/skills/$skillId': {
      id: '/_app/agents/$agentId/skills/$skillId'
      path: '/skills/$skillId'
      fullPath: '/agents/$agentId/skills/$skillId'
      preLoaderRoute: typeof AppAgentsAgentIdSkillsSkillIdRouteImport
      parentRoute: typeof AppAgentsAgentIdRoute
    }
    '/_app/agents/$agentId/sessions/$sessionId': {
      id: '/_app/agents/$agentId/sessions/$sessionId'
      path: '/sessions/$sessionId'
      fullPath: '/agents/$agentId/sessions/$sessionId'
      preLoaderRoute: typeof AppAgentsAgentIdSessionsSessionIdRouteImport
      parentRoute: typeof AppAgentsAgentIdRoute
    }
    '/_app/agents/$agentId/memories/soul': {
      id: '/_app/agents/$agentId/memories/soul'
      path: '/memories/soul'
      fullPath: '/agents/$agentId/memories/soul'
      preLoaderRoute: typeof AppAgentsAgentIdMemoriesSoulRouteImport
      parentRoute: typeof AppAgentsAgentIdRoute
    }
    '/_app/agents/$agentId/memories/profile': {
      id: '/_app/agents/$agentId/memories/profile'
      path: '/memories/profile'
      fullPath: '/agents/$agentId/memories/profile'
      preLoaderRoute: typeof AppAgentsAgentIdMemoriesProfileRouteImport
      parentRoute: typeof AppAgentsAgentIdRoute
    }
    '/_app/agents/$agentId/automations/new': {
      id: '/_app/agents/$agentId/automations/new'
      path: '/automations/new'
      fullPath: '/agents/$agentId/automations/new'
      preLoaderRoute: typeof AppAgentsAgentIdAutomationsNewRouteImport
      parentRoute: typeof AppAgentsAgentIdRoute
    }
    '/_app/agents/$agentId/automations/$jobId': {
      id: '/_app/agents/$agentId/automations/$jobId'
      path: '/automations/$jobId'
      fullPath: '/agents/$agentId/automations/$jobId'
      preLoaderRoute: typeof AppAgentsAgentIdAutomationsJobIdRouteImport
      parentRoute: typeof AppAgentsAgentIdRoute
    }
    '/_app/agents/$agentId/projects/$projectId/': {
      id: '/_app/agents/$agentId/projects/$projectId/'
      path: '/projects/$projectId'
      fullPath: '/agents/$agentId/projects/$projectId/'
      preLoaderRoute: typeof AppAgentsAgentIdProjectsProjectIdIndexRouteImport
      parentRoute: typeof AppAgentsAgentIdRoute
    }
    '/_app/agents/$agentId/skills/$scope/$skillId': {
      id: '/_app/agents/$agentId/skills/$scope/$skillId'
      path: '/skills/$scope/$skillId'
      fullPath: '/agents/$agentId/skills/$scope/$skillId'
      preLoaderRoute: typeof AppAgentsAgentIdSkillsScopeSkillIdRouteImport
      parentRoute: typeof AppAgentsAgentIdRoute
    }
    '/_app/agents/$agentId/automations/goals/$goalId': {
      id: '/_app/agents/$agentId/automations/goals/$goalId'
      path: '/automations/goals/$goalId'
      fullPath: '/agents/$agentId/automations/goals/$goalId'
      preLoaderRoute: typeof AppAgentsAgentIdAutomationsGoalsGoalIdRouteImport
      parentRoute: typeof AppAgentsAgentIdRoute
    }
    '/_app/agents/$agentId/automations/$jobId/edit': {
      id: '/_app/agents/$agentId/automations/$jobId/edit'
      path: '/edit'
      fullPath: '/agents/$agentId/automations/$jobId/edit'
      preLoaderRoute: typeof AppAgentsAgentIdAutomationsJobIdEditRouteImport
      parentRoute: typeof AppAgentsAgentIdAutomationsJobIdRoute
    }
    '/_app/agents/$agentId/projects/$projectId/sessions/$sessionId': {
      id: '/_app/agents/$agentId/projects/$projectId/sessions/$sessionId'
      path: '/projects/$projectId/sessions/$sessionId'
      fullPath: '/agents/$agentId/projects/$projectId/sessions/$sessionId'
      preLoaderRoute: typeof AppAgentsAgentIdProjectsProjectIdSessionsSessionIdRouteImport
      parentRoute: typeof AppAgentsAgentIdRoute
    }
    '/_app/agents/$agentId/automations/$jobId/runs/$runId': {
      id: '/_app/agents/$agentId/automations/$jobId/runs/$runId'
      path: '/runs/$runId'
      fullPath: '/agents/$agentId/automations/$jobId/runs/$runId'
      preLoaderRoute: typeof AppAgentsAgentIdAutomationsJobIdRunsRunIdRouteImport
      parentRoute: typeof AppAgentsAgentIdAutomationsJobIdRoute
    }
  }
}

interface AppAgentsAgentIdAutomationsJobIdRouteChildren {
  AppAgentsAgentIdAutomationsJobIdEditRoute: typeof AppAgentsAgentIdAutomationsJobIdEditRoute
  AppAgentsAgentIdAutomationsJobIdRunsRunIdRoute: typeof AppAgentsAgentIdAutomationsJobIdRunsRunIdRoute
}

const AppAgentsAgentIdAutomationsJobIdRouteChildren: AppAgentsAgentIdAutomationsJobIdRouteChildren =
  {
    AppAgentsAgentIdAutomationsJobIdEditRoute:
      AppAgentsAgentIdAutomationsJobIdEditRoute,
    AppAgentsAgentIdAutomationsJobIdRunsRunIdRoute:
      AppAgentsAgentIdAutomationsJobIdRunsRunIdRoute,
  }

const AppAgentsAgentIdAutomationsJobIdRouteWithChildren =
  AppAgentsAgentIdAutomationsJobIdRoute._addFileChildren(
    AppAgentsAgentIdAutomationsJobIdRouteChildren,
  )

interface AppAgentsAgentIdRouteChildren {
  AppAgentsAgentIdIndexRoute: typeof AppAgentsAgentIdIndexRoute
  AppAgentsAgentIdAutomationsJobIdRoute: typeof AppAgentsAgentIdAutomationsJobIdRouteWithChildren
  AppAgentsAgentIdAutomationsNewRoute: typeof AppAgentsAgentIdAutomationsNewRoute
  AppAgentsAgentIdMemoriesProfileRoute: typeof AppAgentsAgentIdMemoriesProfileRoute
  AppAgentsAgentIdMemoriesSoulRoute: typeof AppAgentsAgentIdMemoriesSoulRoute
  AppAgentsAgentIdSessionsSessionIdRoute: typeof AppAgentsAgentIdSessionsSessionIdRoute
  AppAgentsAgentIdSkillsSkillIdRoute: typeof AppAgentsAgentIdSkillsSkillIdRoute
  AppAgentsAgentIdSkillsNewRoute: typeof AppAgentsAgentIdSkillsNewRoute
  AppAgentsAgentIdTasksTaskIdRoute: typeof AppAgentsAgentIdTasksTaskIdRoute
  AppAgentsAgentIdTasksNewRoute: typeof AppAgentsAgentIdTasksNewRoute
  AppAgentsAgentIdAutomationsIndexRoute: typeof AppAgentsAgentIdAutomationsIndexRoute
  AppAgentsAgentIdSkillsIndexRoute: typeof AppAgentsAgentIdSkillsIndexRoute
  AppAgentsAgentIdTasksIndexRoute: typeof AppAgentsAgentIdTasksIndexRoute
  AppAgentsAgentIdAutomationsGoalsGoalIdRoute: typeof AppAgentsAgentIdAutomationsGoalsGoalIdRoute
  AppAgentsAgentIdSkillsScopeSkillIdRoute: typeof AppAgentsAgentIdSkillsScopeSkillIdRoute
  AppAgentsAgentIdProjectsProjectIdIndexRoute: typeof AppAgentsAgentIdProjectsProjectIdIndexRoute
  AppAgentsAgentIdProjectsProjectIdSessionsSessionIdRoute: typeof AppAgentsAgentIdProjectsProjectIdSessionsSessionIdRoute
}

const AppAgentsAgentIdRouteChildren: AppAgentsAgentIdRouteChildren = {
  AppAgentsAgentIdIndexRoute: AppAgentsAgentIdIndexRoute,
  AppAgentsAgentIdAutomationsJobIdRoute:
    AppAgentsAgentIdAutomationsJobIdRouteWithChildren,
  AppAgentsAgentIdAutomationsNewRoute: AppAgentsAgentIdAutomationsNewRoute,
  AppAgentsAgentIdMemoriesProfileRoute: AppAgentsAgentIdMemoriesProfileRoute,
  AppAgentsAgentIdMemoriesSoulRoute: AppAgentsAgentIdMemoriesSoulRoute,
  AppAgentsAgentIdSessionsSessionIdRoute:
    AppAgentsAgentIdSessionsSessionIdRoute,
  AppAgentsAgentIdSkillsSkillIdRoute: AppAgentsAgentIdSkillsSkillIdRoute,
  AppAgentsAgentIdSkillsNewRoute: AppAgentsAgentIdSkillsNewRoute,
  AppAgentsAgentIdTasksTaskIdRoute: AppAgentsAgentIdTasksTaskIdRoute,
  AppAgentsAgentIdTasksNewRoute: AppAgentsAgentIdTasksNewRoute,
  AppAgentsAgentIdAutomationsIndexRoute: AppAgentsAgentIdAutomationsIndexRoute,
  AppAgentsAgentIdSkillsIndexRoute: AppAgentsAgentIdSkillsIndexRoute,
  AppAgentsAgentIdTasksIndexRoute: AppAgentsAgentIdTasksIndexRoute,
  AppAgentsAgentIdAutomationsGoalsGoalIdRoute:
    AppAgentsAgentIdAutomationsGoalsGoalIdRoute,
  AppAgentsAgentIdSkillsScopeSkillIdRoute:
    AppAgentsAgentIdSkillsScopeSkillIdRoute,
  AppAgentsAgentIdProjectsProjectIdIndexRoute:
    AppAgentsAgentIdProjectsProjectIdIndexRoute,
  AppAgentsAgentIdProjectsProjectIdSessionsSessionIdRoute:
    AppAgentsAgentIdProjectsProjectIdSessionsSessionIdRoute,
}

const AppAgentsAgentIdRouteWithChildren =
  AppAgentsAgentIdRoute._addFileChildren(AppAgentsAgentIdRouteChildren)

interface AppAgentsRouteChildren {
  AppAgentsAgentIdRoute: typeof AppAgentsAgentIdRouteWithChildren
  AppAgentsIndexRoute: typeof AppAgentsIndexRoute
}

const AppAgentsRouteChildren: AppAgentsRouteChildren = {
  AppAgentsAgentIdRoute: AppAgentsAgentIdRouteWithChildren,
  AppAgentsIndexRoute: AppAgentsIndexRoute,
}

const AppAgentsRouteWithChildren = AppAgentsRoute._addFileChildren(
  AppAgentsRouteChildren,
)

interface AppAutomationsRouteChildren {
  AppAutomationsSplatRoute: typeof AppAutomationsSplatRoute
}

const AppAutomationsRouteChildren: AppAutomationsRouteChildren = {
  AppAutomationsSplatRoute: AppAutomationsSplatRoute,
}

const AppAutomationsRouteWithChildren = AppAutomationsRoute._addFileChildren(
  AppAutomationsRouteChildren,
)

interface AppSessionsRouteChildren {
  AppSessionsSplatRoute: typeof AppSessionsSplatRoute
}

const AppSessionsRouteChildren: AppSessionsRouteChildren = {
  AppSessionsSplatRoute: AppSessionsSplatRoute,
}

const AppSessionsRouteWithChildren = AppSessionsRoute._addFileChildren(
  AppSessionsRouteChildren,
)

interface AppSettingsAgentsAgentIdRouteChildren {
  AppSettingsAgentsAgentIdTabRoute: typeof AppSettingsAgentsAgentIdTabRoute
}

const AppSettingsAgentsAgentIdRouteChildren: AppSettingsAgentsAgentIdRouteChildren =
  {
    AppSettingsAgentsAgentIdTabRoute: AppSettingsAgentsAgentIdTabRoute,
  }

const AppSettingsAgentsAgentIdRouteWithChildren =
  AppSettingsAgentsAgentIdRoute._addFileChildren(
    AppSettingsAgentsAgentIdRouteChildren,
  )

interface AppSettingsAgentsRouteChildren {
  AppSettingsAgentsAgentIdRoute: typeof AppSettingsAgentsAgentIdRouteWithChildren
}

const AppSettingsAgentsRouteChildren: AppSettingsAgentsRouteChildren = {
  AppSettingsAgentsAgentIdRoute: AppSettingsAgentsAgentIdRouteWithChildren,
}

const AppSettingsAgentsRouteWithChildren =
  AppSettingsAgentsRoute._addFileChildren(AppSettingsAgentsRouteChildren)

interface AppSettingsRouteChildren {
  AppSettingsAboutRoute: typeof AppSettingsAboutRoute
  AppSettingsAccountRoute: typeof AppSettingsAccountRoute
  AppSettingsAgentsRoute: typeof AppSettingsAgentsRouteWithChildren
  AppSettingsChannelsRoute: typeof AppSettingsChannelsRoute
  AppSettingsCredentialsRoute: typeof AppSettingsCredentialsRoute
  AppSettingsPluginsRoute: typeof AppSettingsPluginsRoute
  AppSettingsProvidersRoute: typeof AppSettingsProvidersRoute
  AppSettingsSandboxRoute: typeof AppSettingsSandboxRoute
  AppSettingsUsersRoute: typeof AppSettingsUsersRoute
  AppSettingsIndexRoute: typeof AppSettingsIndexRoute
}

const AppSettingsRouteChildren: AppSettingsRouteChildren = {
  AppSettingsAboutRoute: AppSettingsAboutRoute,
  AppSettingsAccountRoute: AppSettingsAccountRoute,
  AppSettingsAgentsRoute: AppSettingsAgentsRouteWithChildren,
  AppSettingsChannelsRoute: AppSettingsChannelsRoute,
  AppSettingsCredentialsRoute: AppSettingsCredentialsRoute,
  AppSettingsPluginsRoute: AppSettingsPluginsRoute,
  AppSettingsProvidersRoute: AppSettingsProvidersRoute,
  AppSettingsSandboxRoute: AppSettingsSandboxRoute,
  AppSettingsUsersRoute: AppSettingsUsersRoute,
  AppSettingsIndexRoute: AppSettingsIndexRoute,
}

const AppSettingsRouteWithChildren = AppSettingsRoute._addFileChildren(
  AppSettingsRouteChildren,
)

interface AppTasksRouteChildren {
  AppTasksTaskIdRoute: typeof AppTasksTaskIdRoute
}

const AppTasksRouteChildren: AppTasksRouteChildren = {
  AppTasksTaskIdRoute: AppTasksTaskIdRoute,
}

const AppTasksRouteWithChildren = AppTasksRoute._addFileChildren(
  AppTasksRouteChildren,
)

interface AppRouteChildren {
  AppAgentsRoute: typeof AppAgentsRouteWithChildren
  AppAutomationsRoute: typeof AppAutomationsRouteWithChildren
  AppRecallyRoute: typeof AppRecallyRoute
  AppSchedulerRoute: typeof AppSchedulerRoute
  AppSessionsRoute: typeof AppSessionsRouteWithChildren
  AppSettingsRoute: typeof AppSettingsRouteWithChildren
  AppTasksRoute: typeof AppTasksRouteWithChildren
}

const AppRouteChildren: AppRouteChildren = {
  AppAgentsRoute: AppAgentsRouteWithChildren,
  AppAutomationsRoute: AppAutomationsRouteWithChildren,
  AppRecallyRoute: AppRecallyRoute,
  AppSchedulerRoute: AppSchedulerRoute,
  AppSessionsRoute: AppSessionsRouteWithChildren,
  AppSettingsRoute: AppSettingsRouteWithChildren,
  AppTasksRoute: AppTasksRouteWithChildren,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
  ProfileRoute: ProfileRoute,
  DocsSplatRoute: DocsSplatRoute,
  STokenRoute: STokenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
